version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_DB: '${TYPEORM_DATABASE}'
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 8080:5432
    volumes:
      - ./pgdata/data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgdata/pgadmin:/root/.pgadmin
    ports:
      - '5050:80'
  api:
    environment:
      - NODE_ENV:${NODE_EN}
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['yarn', 'start:${NODE_EN}']
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
